language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -U beautifulsoup4
  - pip install pytest-cov
  - pip install codecov
script:
  - pytest --cov=./
after_success:
  - codecov -t $CODECOV_TOKEN